datastorage:
  dirty_seconds: 5
  days_clear_after_inactive: 180 #Clear this player's cosmetics data if they have not logged on in this many days
  
permissions:
  scycosmetics: scycosmetics.base
  scycosmetics_afk: scycosmetics.afk
  scycosmetics_help: scycosmetics.help
  scycosmetics_give: scycosmetics.give
  scycosmetics_givew: scycosmetics.givew
  scycosmetics_take: scycosmetics.take
  scycosmetics_giveall: scycosmetics.giveall
  scycosmetics_takeall: scycosmetics.takeall
  
  semote: scycosmetics.emote
  
  
  
inventory_settings:
  base_inventory:
    title: '&cScyCosmetics Menu'
    size: 54
    items:
      arrow_trail:
        material: ARROW #To make this a head, use "head;VALUE". Get value from here: https://minecraft-heads.com/
        display_name: '&bArrow Trails'
        lore:
          - '&3Make your shots sexy'
        slot: 17 #Don't change this
      last_words:
        material: PAPER
        display_name: '&2Last Words'
        lore:
          - '&aCurse your enemies in your final breath <3'
        slot: 15 #Don't change this
      player_trail:
        material: LEATHER_BOOTS
        display_name: '&aPlayer Trails'
        lore:
          - '&3Moves like jagger'
        slot: 33 #Don't change this
      emote_equipment:
        material: TOTEM_OF_UNDYING 
        display_name: '&3Emotes'
        lore:
          - '&3Express yourself'
        slot: 11 #Don't change this
      prefix:
        material: NAME_TAG 
        display_name: '&cPrefixes'
        lore:
          - '&4Fun symbol'
        slot: 9 #Don't change this
      kill_effect:
        material: IRON_SWORD 
        display_name: '&4Kill Effects'
        lore:
          - '&cMake total annihilation even better'
        slot: 27 #Don't change this
      afk_effect:
        material: COBWEB 
        display_name: '&9AFK Effects'
        lore:
          - '&3Afk particles!'
        slot: 22 #Don't change this
      log_message:
        material: LEVER 
        display_name: '&1Log Messages'
        lore:
          - '&3Join and leave in style'
        slot: 35 #Don't change this
      title:
        material: WRITABLE_BOOK 
        display_name: '&eTitles'
        lore:
          - '&3Demand respect'
        slot: 29 #Don't change this
      
      info: #YET TO BE IMPLEMENTED
        material: BEACON
        display_name: '&bCosmetic Info'
#        lore: #Add any additional lore you want here
#          - ''
        slot: 49
        enabled: true
  
cosmetics:
  display_items:
    lore: #Option to automatically apply the tier and buy price of an item to the lore
      append_tier: true
  default_buy_prices:
    common: 50
    uncommon: 75
    rare: 100
    epic: 150
    special: 200
    legendary: 300
    mythic: 500
    artifact: 100000
    seasonal: 500
    lore: 100000
    
#When choosing a tier, it sums all the weights and the percent chance is the weight of that tier / sum. 
#If no cosmetic of that tier exists, it gives the highest tier that is lower than the one chosen 
#("lower" in ordering in config below - but don't change this order)
#(or money if no common exists)
give_weighted: #/scos givew command
  weights: 
    common: 40.01 #Can be decimals
    uncommon: 20
    seasonal: 40 #The odds of getting a seasonal cosmetic are high during the season.
    rare: 15
    epic: 8
    special: 7 
    legendary: 5  
    mythic: 4
    artifact: 1
    lore: 0
  
misc:
  #in seconds. Given to players if a special feature stops working so players can notify admin of the issue.
  special_feature_error_cooldown: 5
  #in seconds. Prevents use of emotes until this cooldown passes.
  emote_cooldown: 20
  #in TICKS. Ticks until armor stand spawns after running the command
  emote_delay_ticks: 40 
  #A number (can have decimals) between 0-100 representing percent chance a player wins vault money in place of a cosmetic.
  give_random_vault_chance: 10.0 
  #How much money to give a player who wins vault money in place of a cosmetic. No effect if give_random_vault_chance = 0
  give_random_vault_amount: 50.0
  #How much money to give a player if they already have all cosmetics of the specified type and tier unlocked. Set to 0 to give them nothing
  give_vault_all_unlocked: 100.0
  
messages:
  prefix: '&8[&bCosmetics&8]'
  no_permission: '&cYou do not have permission for this command.'
  scycos_give_success: '&aSuccessfully gave player &2{player} &aaccess to the cosmetic &2{cosmetic}&a.'
  scycos_giveall_success: '&aSuccessfully gave player &2{player} &aaccess to all cosmetics of specified type and tier.'
  scycos_take_success: '&aRemoved access to cosmetic &2{cosmetic} &afrom player &2{player}&a.'
  scycos_takeall_success: '&aRemoved all cosmetics of specified type and tier from &2{player}&a.'
  scycos_receive_success: '&aYou have unlocked access to the cosmetic &2{cosmetic}&a.'
  scycos_receiveall_success: '&aYou have unlocked access to all cosmetics of type &2{type} &aand tier &2{tier}&a.'
  emote_spawning: '&aSpawning emote...'
  random_vault_money_given: '&aYou have been awarded &2{amount}GP &ainstead of a cosmetic!'
  random_vault_no_money_given: '&cYou did not win a random cosmetic :('
  all_cos_unlocked_given_money: '&aYou have been awarded &2${amount} &ainstead of a cosmetic because you have all available cosmetics unlocked!'
  all_cos_unlocked_no_reward: '&cYou were not given a cosmetic because they were all already unlocked.'
  player_set_afk: "&aYou are now afk."
  
  error_player_not_found: '&cThe player &4{player} &cis not online or does not exist.'
  error_player_only_cmd: '&cSorry console! Only players can perform this command :('
  error_invalid_cosmetic_id: '&cThe specified cosmetic id does not exist.'
  error_invalid_cosmetic_type: '&cThe specified cosmetic type does not exist.'
  error_invalid_cosmetic_tier: '&cThe specified cosmetic tier does not exist.'
  error_particle_data: '&cError! Unable to do special effect. Custom data does not match particle type. Please report to staff, this is a bug.'
  error_emote_cooldown: '&cYou must wait a few seconds before emoting again!'
  error_emote_locked: '&cYou have not unlocked this emote!'
  error_insufficient_funds: '&cYou do not have enough money!'
  error_take_cosmetic_already_locked: '&cThe player specified has this cosmetic already locked.'
  error_emote_spectator: "&cCannot emote while in spectator mode!"