main: xyz.scyllasrock.ScyCosmetics.spigot.Main
name: ScyCosmetics
version: 1.0
author: kwilk
api-version: 1.13
description: Flexible cosmetics for players

commands:
  scycosmetics:
    aliases: [scycosmetic, cosmetics]