main: xyz.scyllasrock.ScyCosmetics.spigot.Main
name: ScyCosmetics
version: 1.0
author: kwilk
api-version: 1.13
depend: [ScyUtility]
softdepend: [PlaceholderAPI, PremiumVanish, JetsAntiAFKPro]
description: Flexible cosmetics for players

commands:
  scos:
    aliases: [scycosmetics]
  semote: 